# Nginx as reverse proxy for Blue-Green deployment

# --- Main / global settings (I kept these as standard for Nginx) ---
user nginx;                                    # Run Nginx as user nginx, not root, for security
worker_processes auto;                         # Set auto so it uses one worker per CPU core
error_log /var/log/nginx/error.log warn;       # Log errors here; warn = only warnings and worse
pid /var/run/nginx.pid;                        # Nginx writes its PID here so we can reload/stop it

# --- Events block (required by Nginx) ---
events {
    worker_connections 1024;                   # Allow up to 1024 connections per worker
}

# --- HTTP block: defines how Nginx handles web traffic ---
http {
    include /etc/nginx/mime.types;             
    default_type application/octet-stream;     
    sendfile on;                              
    keepalive_timeout 65;                      

    # --- Blue/Green: In active.conf we have defined which one is active env
    include /etc/nginx/conf.d/active.conf;

    # --- First server block: frontend on port 80 ---
    # When user opens http://localhost/ everything is forwarded to frontend_active
    server {
        listen 80;                            
        server_name localhost;                 # Accept requests for localhost
        location / {                           
            proxy_pass http://frontend_active; # Send to active frontend (Blue or Green)
            proxy_http_version 1.1;            
            proxy_set_header Host $host;      
            proxy_set_header X-Real-IP $remote_addr;            
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;   
            proxy_set_header X-Forwarded-Proto $scheme;         
        }
    }

    # --- Second server block: backend API on port 3001 ---
    # The frontend calls http://localhost:3001/api/...; forwarding that to backend_active.
    server {
        listen 3001;                           
        server_name localhost;
        location / {                           # All API paths go through here
            proxy_pass http://backend_active;  # Send to active backend (Blue or Green)
            proxy_http_version 1.1;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }
    }
}
